Feature/fyp 10/sidebar button creation
GR-DevTeam/fyp pull request #12
Opened 2021-09-08 18:08 UTC by FrancoMartinetto

-) Se creo el componente SideBarButton que contiene un botón,con un texto y un icono listo para ser accedido desde props, junto con un estilado de acuerdo a diseño,luego se importo a la App para su posterior prueba de componentes(se deberia borrar e implementar en la SideBar antes de comitear a Main)

2021-09-09 19:43 UTC, MaxHMoyano requested changes

2021-09-09 21:27 UTC, FrancoMartinetto commented on src/App.tsx
> +import { faMale, faSearch } from '@fortawesome/free-solid-svg-icons';
Done

2021-09-09 21:27 UTC, FrancoMartinetto commented on src/App.tsx
> +        <SidebarButton icon={faMale} text="Hola Maxi" />
Done

2021-09-10 21:09 UTC, merged

2021-09-10 21:09 UTC, MaxHMoyano approved these changes