Feature/fyp 7/sidebar component
GR-DevTeam/fyp pull request #14
Opened 2021-09-16 15:17 UTC by juanCruzSalina

# Description

Created a new component Sidebar, added the Links components, and moved it into the molecules folder.  Added the stpryboook where I performed all respective tests.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-09-17 14:59 UTC, FrancoMartinetto approved these changes
Veo varios problemas con el texto,sobre todo cuando se agranda,pero que Maxi lo revise bien al codigo

2021-09-20 18:48 UTC, MaxHMoyano requested changes

2021-09-20 18:48 UTC, MaxHMoyano commented on src/components/molecule/Sidebar/Sidebar.stories.tsx
> +  data: [
El nombre para la `data` deberia ser `items`. Asi se entiende mejor a que se refiere.

2021-09-20 18:48 UTC, MaxHMoyano commented on src/components/molecule/Sidebar/Sidebar.stories.tsx
> +      onHoverColor: '#FE8F29',
Asegurate de usar los colores del tema global y no cualquier hex color que podria no ser parte del tema

2021-09-20 18:48 UTC, MaxHMoyano commented on src/components/molecule/Sidebar/Sidebar.tsx
> +`;
Tanto el elemento `ul` como el `li` son innecesarios. El wrapper deberia ser un component flex en modo `column` y nos ahorraria el trabajo de renderizar 3 componentes diferentes.

2021-09-21 13:31 UTC, MaxHMoyano submitted a review, later dismissed

2021-09-21 15:18 UTC, MaxHMoyano approved these changes

2021-09-21 18:03 UTC, merged